### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by ghost** [behrenhoff/parse-clang-tidy#1]
Hello!
Sorry for contacting you in this ugly way, but I did not find any usable channel. I have a few question regarding this output simplifier. Could I borrow a few minutes of your time?

**Comment by behrenhoff** [comment]
Sure, what is your problem/question? And: who did you come across this project?

You might want to adapt a few things before using this project - unless you are using it for ROOT (root.cern.ch). I am dealing with a few quirks with the ROOT build system here to generate valid links.

**Comment by ghost** [comment]
Thank you for the quick response. I am not sure what do you mean by root project, so the simpliest thing would be to explain my problem in detail :)
I have a task at my workspace to integrate clang tidy into a jenkins based build toolchain. I have a custom build clang tidy (v5.0.1) and I use the run-clang-tidy.py with a compilation database. Also, I am using self-defined custom checkers. My problem is, that i cannot parse properly the output in jenkins pipeline. The python script floods the console with random warning messages (more than 1k lines), and only a few lines (under 10) are referenci g to my custom checker. I only need those few lines. The first question is, that can I use your code at a company infrastructure? If so, is your script (with minimal modifocation) capable of solving my problem?

**Comment by behrenhoff** [comment]
Ok, so maybe more info about this project:
a) ROOT is a big Data Analysis framework
b) when running clang-tidy over ROOT (enabling all checks), you get several GB (!) of text output. So I needed some code to make this more usable. This script parses the logs, "uniquifies" them and saves them into a sqlite3 database for later usage (either your own usage or to display the results on a small webpage).

You need to:
a) patch run-clang-tidy.py (search for a "write" and replace it with "print" or add a "flush") - don't remember where it was. See next comment.
b) adapt the path names in parse-clang-tidy-log.pl and run it (run clang-tidy > logfile.txt, then parse-clang-tidy-log.pl  logfile.txt; you can also create multiple log files) It will insert into a Sqlite3 file "result.sqlite" and also create "test.js". View the results by opening "test.html" in a browser. As an alternative, look at the database or run gui.pl to get a small webpage.
You might need a include_to_src.json file (it stores include paths mappings / probably an empty file, or a file containing only {}, will be enough)

Probably I should expand the documentation....

**Comment by behrenhoff** [comment]
The clang-tidy patch:

```
+++ b/clang-tidy/tool/run-clang-tidy.py
@@ -167,7 +167,7 @@ def run_tidy(args, tmpdir, build_path, queue, lock, failed_files):
     if proc.returncode != 0:
       failed_files.append(name)
     with lock:
-      sys.stdout.write(' '.join(invocation) + '\n' + output.decode('utf-8') + '\n')
+      print(' '.join(invocation) + '\n' + output.decode('utf-8') + '\n')
       if len(err) > 0:
         sys.stderr.write(err.decode('utf-8') + '\n')
     queue.task_done()

```

**Comment by ghost** [comment]
Thank you for your time and help!
I'll try it tomorrow and give you feedback how it went.

**Comment by behrenhoff** [comment]
I've updated the README.md. Please test + enjoy!

**Comment by behrenhoff** [comment]
Just a question: did you try this parser? Did it work for you? Can I close this issue or do you need more help/info?

**Comment by ghost** [comment]
Hello. Unfortunatley I haven't finished my task yet, but looks really promising, thank you! I think I'll close the issue, and get back if something extraordinary comes up :)
